### ISSUE TITLE
Dead discord invitation link

### ISSUE THREAD

**Issue by DesireSai** [Dangetsu/vnr_server#1]
Hello there! I wanted to join your server but the link is dead ;~;

**Comment by Ayawaska** [comment]
> Hello there! I wanted to join your server but the link is dead ;~;

https://discord.gg/t68zYZ

**Comment by Ayawaska** [comment]
> Hello there! I wanted to join your server but the link is dead ;~;

https://discord.gg/t68zYZ

**Comment by DesireSai** [comment]
> > Hello there! I wanted to join your server but the link is dead ;~;
> 
> https://discord.gg/t68zYZ

Thank you so much! ^_^
